### ISSUE TITLE
Data request

### ISSUE THREAD

**Issue by Smirrie** [PyPSA/pypsa-za#1]
Is there any possibility to obtain the data listed in the snakefile. For example:

* "data/Original_UTM35north/sa_lcov_2013-14_gti_utm35n_vs22b.tif"
* 'data/afripop/ZAF15adjv4.tif'
* "data/EIA_hydro_generation_2011_2014.csv"

I heard of your project at WindAc conference.

**Comment by coroa** [comment]
Hi Smirrie,

thanks for the interest! The problem is that I cannot publically put the data online, since this would violate the license conditions; even though all of it is available online, except for the system energy time-series.

The data in question is (I'll add links where possible):

- [afripop](http://www.worldpop.org.uk/data/summary/?doi=10.5258/SOTON/WP00246) (Population density from energydata.info)
- [Wind_PV_Normalised_Profiles.xlsx](https://www.csir.co.za/csir-energy-centre-documents) (Results of the Wind and Solar PV Aggregation Study of IWES and CSIR)
- [EIA_hydro_generation_2011_2014.csv](http://tinyurl.com/EIA-hydro-gen-ZA-MZ-2011-2014) (Yearly hydro generation numbers from EIA)
- [Power_corridors/](https://egis.environment.gov.za/data_egis/node/109) (GIS shapes of the power corridors)
- [REDZ_DEA_Unpublished_Draft_2015/](https://egis.environment.gov.za/data_egis/node/109) (GIS shapes of REDZ)
- [SACAD_OR_2017_Q2/](https://egis.environment.gov.za/data_egis/node/109) (GIS shapes of Conservation areas)
- [SAPAD_OR_2017_Q2/](https://egis.environment.gov.za/data_egis/node/109) (GIS shapes of Protected areas)
- SystemEnergy2009_13.csv (System load, available on request from ESKOM)
- [Original_UTM35north/](https://egis.environment.gov.za/data_egis/node/109) (GIS landuse data, "Land Cover Thematic Data 2013-14, 72 Classes")

Please mail me (hoersch@fias.uni-frankfurt.de) privately for now. I will discuss with the CSIR next week on what are the best options to make this data available more easily.

**Comment by coroa** [comment]
All the links are also provided in the conference paper available from [preprint](https://arxiv.org/pdf/1710.11199).

**Comment by coroa** [comment]
It turns out all of the data is either from the CSIR, under public domain or CC-BY (afripop), so I can actually redistribute it!

Please find a bundle of the data at https://fias.uni-frankfurt.de/~hoersch/pypsa_models/pypsa-za/data_package.tar.xz, which you will have to extract into the data sub-directory. I will add dynamic downloading capabilities using the remote provider feature of snakemake soon.

**Comment by coroa** [comment]
(Side-note, as in not relevant to this issue,  you can install all software dependencies using `conda create -f environment.yml` now, except for the gurobi solver)

**Comment by jcformanek** [comment]
Hi there, I am really interested in using this software. But the data link does not work any more. Any chance you can assist me with getting the data?
